#!/bin/csh
# run a sequence of simulations 1 week 1 month 3 months and annuall
# and use extract.
echo $1
echo "spring week simulation with cellular_shd_jan-feb.cfg"
date
&>/dev/null time bps -mode text -file cellular_shd_jan-feb.cfg -p spr silent
echo "starting extact..."
date
./extract cellular_shd_spr.res
echo "finished spring week"
echo "jan-feb simulation with cellular_shd_jan-feb.cfg"
date
&>/dev/null time bps -mode text -file cellular_shd_jan-feb.cfg -p win1 silent
echo "starting extact..."
date
./extract cellular_shd_jan-feb.res
date
echo "finished jan-feb months"
echo "summer simulation with cellular_shd_jan-feb.cfg"
&>/dev/null time bps -mode text -file cellular_shd_jan-feb.cfg -p sum silent
date
echo "starting extact..."
./extract cellular_shd_sum.res
echo "finished summer"
echo "annual simulation with cellular_shd_jan-feb.cfg"
date
&>/dev/null time bps -mode text -file cellular_shd_jan-feb.cfg -p annual silent
date
echo "starting extact..."
./extract cellular_shd_annual.res
date
echo "finished annual"


