#!/bin/bash
# run may 20tsph simulation to be equivalent to EP FD run.
echo $1
echo $1 >$1
echo "seq may simulation with stone_simi_1890_may20.cfg"
echo "seq may simulation with stone_simi_1890_may20.cfg" >>$1
date
date >>$1
/usr/bin/time bps -mode text -file stone_simi_1890_may20.cfg -p may silent
date
date >>$1
echo "starting sequential may extact..."
echo "starting sequential may extact..." >>$1
./extractmonthly stone_simi_1890_may.res
date
date >>$1
echo "finished may extracts"
echo "finished may extracts" >>$1


