#!/bin/bash
# run sequential & parallel of simulations may june july august and extract in
# sequence and use extract.
echo "seq may simulation with stone_simi_1890.cfg"
date
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p may silent >/dev/null
date
echo "starting sequential may extact..."
./extractmonthly stone_simi_1890_may.res
date
echo "seq june simulation with stone_simi_1890.cfg"
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p june silent >/dev/null
date
echo "starting june extact..."
./extractmonthly stone_simi_1890_june.res
date
echo "seq july simulation with stone_simi_1890.cfg"
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p july silent >/dev/null
date
echo "starting july extact..."
./extractmonthly stone_simi_1890_july.res
date
echo "seq august..."
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p august silent >/dev/null
date
echo "starting august extact..."
./extractmonthly stone_simi_1890_august.res
date
echo "pausing 10 seconds"
sleep 10
rm *.res
date
echo "seq summer simulation with stone_simi_1890.cfg"
date
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p summer silent >/dev/null
date
echo "pausing 10 seconds"
rm *.res
sleep 10
date
echo "par may simulation with stone_simi_1890.cfg"
date
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p may silent & >/dev/null
date
echo "par june simulation with stone_simi_1890.cfg"
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p june silent & >/dev/null
date
echo "par july simulation with stone_simi_1890.cfg"
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p july silent & >/dev/null
echo "august not done in background..."
date
/usr/bin/time bps -mode text -file stone_simi_1890.cfg -p august silent >/dev/null
date
echo "finished sequential extracts"


